# Book settings
title:
author: Holly Krambeck
logo: docs/images/logo.png

repository:
    url: https://github.com/Holly-Transport/Google_Stock_Trend_Track
    branch: main

html:
    home_page_in_navbar: false
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://holly-transport.github.io/Google_Stock_Trend_Track

only_build_toc_files: true
